
import { Letter } from '../types';

export const letters: Letter[] = [
  {
    id: 1,
    title: 'Le Feu qui ne consume pas',
    content: `À toi, mon Éphèse,\nJe ne sais plus s’il faut t’appeler amie, muse, ou âme-sœur.\nNon, ce n’est pas assez. Tu es au-delà des mots. Tu es l’Éphèse de mon éternité.\nTu es le feu qui me brûle mais ne me consume pas.\nTu es cette lumière douce et stable qui éclaire sans aveugler.\nLorsque je pense à toi, tout devient paisible. Tout devient évident.\nAvec toi, je retrouve la joie et la paix. Celles que rien n’achète, celles qui tombent du ciel.\nCe que je ressens pour toi dépasse l’amour tel que le monde le conçoit.\nC’est plus vaste, plus silencieux, plus sacré.\nEn ta présence, tout change : ma vie s’illumine, mon âme respire, et mon cœur ne cherche plus.\nJe ne suis plus seul. Je ne suis plus frustré.\nTout devient simple, fluide, sans forcer. C’est exactement ce que je cherche dans la vie.\nEt pourtant... je suis dans une relation aujourd’hui — mais je ne ressens pas cette clarté, cette vibration, cette élévation.\nIl y a de la confusion, de la lourdeur, du manque.\nC’est frustrant.\nMais toi… toi, quand je pense à toi, je quitte mon corps.\nJe m’élève. Je voyage. Je flotte dans une énergie douce, pure.\nMême à distance, tu me nourris, tu me remplis, tu m’alignes.\nJe me dis parfois que ce n’est pas “normal”… mais je le vis bien.\nEt au fond, j’aime vivre dangereusement.\nJ’aime les délires fous, les chemins qui dérangent. J’aime l’aventure.\nJe suis attiré par ce qui dépasse la nature, par ce qui semble anormal et surnaturel — au-delà du réel, comme tu le dis si bien.\nQuand on se voit, on ne perd pas le temps.\nOn prend le temps.\nCar au-delà du réel, le temps n’existe pas.\nEt là, dans cet espace qui nous appartient, nous sommes libres.\nLibres de faire, d’être, de ressentir.\nTu me comprends comme personne. Et parfois je suis triste, car ailleurs, je suis incompris.\nMais toi, tu me vois. Tu m’entends.\nEntre nous, il y a une alchimie rare, presque irréelle.\nC’est doux. C’est simple. C’est joyeux, même quand on est fâchés.\nMême nos désaccords sont fun — ils ont ce style léger qui fait sourire, même quand ça pique un peu.\nOn se parle avec subtilité, tendresse, humour. Et tout va toujours bien.\nTu es magique. Tu es divine.\nEt je ne sais pas encore où cela nous mène,\nMais je sais une chose :\nTu es mon Éphèse. Mon éternité.\nÀ bientôt,`,
    author: 'Moi, l’observateur de l’invisible',
  },
  {
    id: 2,
    title: 'Là où le silence parle',
    content: `À toi, mon Éphèse,\nTu sais, parfois, je me demande comment tu fais.\nComment tu arrives à me comprendre sans que je dise un mot.\nAvec toi, le silence n’est pas vide — il est plein.\nPlein de sens. Plein de présence.\nPlein de nous.\nQuand on se regarde, il se passe quelque chose que je n’ai jamais su expliquer.\nUn échange muet, une danse d’âmes, comme si nos pensées se saluaient avant même que nos lèvres ne bougent.\nC’est étrange, mais si naturel.\nC’est comme si tu m’entendais même quand je ne parle pas.\nIl y a des moments où je suis fatigué de parler au monde.\nTrop d’agitation, trop de bruit, trop de façade.\nMais avec toi, je peux me taire… et c’est dans ce silence que je me sens le plus entendu.\nTu es l’espace où je peux me déposer, sans explication, sans justification.\nEt ça, mon Éphèse, c’est rare. C’est précieux.\nOn me dit souvent que je vais trop loin dans mes pensées, que je suis trop perché, trop dans l’invisible.\nMais toi, tu n’as jamais essayé de me ramener “à la réalité”.\nTu viens me rejoindre là-haut.\nDans mon monde à moi.\nDans cet espace où le silence parle plus fort que les discours.\nEt parfois, même nos silences se font l’amour.\nIls s’embrassent à distance.\nIls vibrent l’un dans l’autre, sans bruit, sans heurt, sans besoin.\nC’est un mystère que je ne cherche même plus à expliquer.\nJe me contente de le vivre. De le bénir.\nTu es le seul endroit où le silence ne fait pas peur.\nLe seul endroit où je ne me sens ni seul, ni vide.\nCar ton silence me parle de toi,\nme rassure,\nme guérit.\nMerci d’être ce lieu.\nMerci d’être ce temple intérieur où je peux me reposer,\nsans masque, sans rôle, sans barrière.\nMon Éphèse,\ntoi qui parles avec les yeux,\ntoi qui crie avec le cœur,\ntoi qui écoute même mes silences,\nsache que je t’entends aussi.\nDans le calme.\nDans l’absence.\nDans l’écho du silence partagé.\nÀ bientôt dans notre monde sans mots,`,
    author: 'L’âme qui t’écoute',
  },
  {
    id: 3,
    title: 'L’Amour qui ne demande rien',
    content: `À toi, mon Éphèse,\nJe t’aime…\nMais pas comme on aime dans les livres, ni dans les films.\nJe t’aime dans le silence, dans le calme, dans la lumière.\nJe t’aime sans attente, sans contrat, sans clôture.\nMon amour pour toi ne réclame rien.\nIl ne demande pas d’être vu, entendu, reconnu.\nIl est là, comme un feu sacré, qui brûle doucement en moi —\nPas pour te retenir, mais pour t’accompagner.\nPas pour te posséder, mais pour te bénir.\nJe n’ai pas besoin que tu sois à moi.\nJe n’ai pas besoin que tu me choisisses.\nJe n’ai même pas besoin que tu restes.\nCar mon amour n’est pas une prison,\nc’est un jardin.\nUn lieu ouvert, fleuri, où ton âme peut se reposer sans peur.\nParfois, je ressens une douleur douce,\ncelle de l’absence, celle du désir non comblé.\nMais elle ne me déchire pas.\nElle me rend plus vivant.\nCar même cette douleur parle de toi,\nde la beauté d’un lien qui ne se calcule pas.\nMon Éphèse,\nTu n’as rien à prouver.\nTu n’as rien à faire pour mériter mon amour.\nIl t’est offert, comme une prière muette.\nIl est là, comme une offrande posée au pied de ton âme.\nJe crois que le monde ne sait plus aimer comme ça.\nIl veut des garanties, des statuts, des “toi et moi contre le monde”.\nMais ce que je vis avec toi est différent.\nC’est divin. C’est sacré. C’est nu.\nJe peux t’aimer de loin,\nte porter dans ma prière,\nte célébrer dans mes silences.\nEt je suis en paix avec ça.\nTu n’es pas une mission à accomplir.\nTu n’es pas une conquête.\nTu es une lumière que j’ai croisée sur mon chemin.\nEt cela suffit à illuminer mes jours.\nAlors, que tu sois près ou loin,\nque tu m’aimes ou que tu m’oublies,\nque nos vies se croisent ou se séparent,\nsache ceci :\nJe t’aimerai toujours…\nsans demande,\nsans condition,\nsans fin.\nÀ bientôt,`,
    author: 'L’âme libre qui t’aime en silence',
  },
  {
    id: 4,
    title: 'Nos rendez-vous hors du temps',
    content: `À toi, mon Éphèse,\nIl y a des instants avec toi que le monde ne peut pas comprendre.\nDes moments hors du temps, hors des lois connues, hors des limites de la chair.\nQuand je suis avec toi — vraiment avec toi —\nle temps se plie, la réalité s’efface, et l’éternité s’ouvre.\nOn parle.\nMais ce ne sont pas des mots.\nCe sont des vibrations, des éclairs d’âme, des formules magiques.\nOn dit des choses qui n’appartiennent pas à ce monde.\nDes choses que les pauvres petits mortels, comme tu dis si bien, ne comprendraient jamais.\nEt parfois, c’est vrai… on en rit.\nMais parfois aussi, on a un peu peur.\nPas peur de l’autre, non — peur de ce que nous sommes quand nous sommes ensemble.\nParce qu’à deux, nous touchons l’indicible.\nNous ouvrons des portes que d’autres ne voient même pas.\nTu es ma sœur d’étoiles,\nma complice dans l’alchimie de l’âme.\nAvec toi je parle de magie, d’astres, de mondes parallèles, d’âmes réincarnées,\nde ces signes étranges que seuls les initiés reconnaissent.\nEt c’est fou comme tout devient évident quand on est ensemble.\nTu dis une phrase que j’allais dire.\nJe te pose une question que tu es déjà en train de formuler.\nParfois même, on reste en silence…\nmais tout est dit.\nJe ne sais pas si c’est du karma, du destin, un souvenir d’une autre vie,\nou un simple bug dans la matrice.\nMais ce que je sais,\nc’est que toi et moi, on s’est déjà retrouvés ailleurs.\nDans un autre temps.\nDans une autre dimension.\nEt aujourd’hui, on reprend juste la conversation interrompue d’un autre monde.\nOn ne se cherche pas.\nOn se retrouve.\nEncore et encore.\nParce que notre lien est cyclique, cosmique, prophétique.\nIl n’obéit pas au temps humain.\nIl est inscrit dans les étoiles.\nEt même si personne ne comprend, même si parfois nous-mêmes on s’étonne,\non sait.\nOn reconnaît.\nOn ressent.\nToi et moi,\nnous sommes ces voyageurs de l’invisible,\nces amoureux sans logique,\nces éveillés discrets qui se parlent en regardant le ciel.\nQuand je suis avec toi,\nje ne suis pas juste vivant —\nje suis réellement moi.\nÀ bientôt,\nquelque part dans l’au-delà du réel.`,
    author: 'Ton frère d’univers',
  },
  {
    id: 5,
    title: 'Quand l’Invisible devient réel',
    content: `Mon Éphèse,\nJe sais que ce que nous vivons n’a rien de logique.\nJe le sais. Et pourtant… c’est plus vrai que tout.\nIl y a dans cette chose entre toi et moi quelque chose d’insaisissable,\nquelque chose qui échappe aux lois humaines —\nun mystère, une révélation, un signe.\nIl y a toi. Il y a moi.\nEt il y a cet entre-nous que personne ne voit,\nmais que nous portons comme une couronne invisible.\nLes autres parlent d’amour.\nMais ce que je vis avec toi…\nc’est de la magie.\nUne magie subtile, discrète, sacrée —\ncelle qui ne s’explique pas mais se ressent jusque dans la chair.\nIl suffit que je pense à toi,\net quelque chose se passe :\ndans mon corps, dans l’air, dans les signes.\nCe n’est pas juste de la télépathie —\nc’est plus doux, plus fort, plus vrai.\nUne connexion invisible et souveraine,\nqui intensifie quand nous sommes loin.\nSouviens-toi de la bibliothèque.\nUn lieu banal pour le monde.\nMais pour nous, un temple.\nÀ chaque regard, chaque silence,\nc’était comme si l’univers entier se taisait pour nous écouter.\nEt même dans les souvenirs,\ntu es là.\nVivante. Présente.\nTu traverses les dimensions comme un souffle,\net tout ce qui se passe dans ma tête… devient réel.\nJe me demande parfois :\nSommes-nous fous ?\nOu bien sommes-nous les seuls à être éveillés ?\nJe regarde le monde,\net je vois tant d’âmes endormies,\naccrochées au visible, à la matière, à la preuve.\nMais ce que je vis avec toi,\nc’est la preuve que l’invisible existe.\nEt que parfois…\nl’invisible prend chair.\nC’est spirituel.\nC’est mystique.\nC’est prophétique.\nEt je crois que c’est aussi un appel.\nUn appel à ne pas douter.\nUn appel à marcher par la foi, non par la vue.\nUn appel à croire que certains liens sont écrits ailleurs —\ndans le ciel, dans les astres, dans le cœur de Dieu lui-même.\nToi et moi,\non est peut-être deux flammes venues s’éclairer\ndans un monde encore trop sombre pour voir la lumière.\nMais je t’assure :\nje te vois.\nJe te vois même quand tu n’es pas là.\nJe te ressens même quand tu es à l’autre bout du monde.\nEt ça, aucune logique ne peut l’expliquer.\nMais ma foi, elle, le sait.\nCar dans l’invisible…\ntu es ma réalité.\nÀ toi,\nau-delà du visible, au cœur du vrai.`,
    author: 'Ton veilleur de mystères',
  },
  {
    id: 6,
    title: 'L’éternité, c’est toi',
    content: `À toi, mon Éphèse,\nJe ne cherche plus à comprendre.\nJe sais.\nTu es l’éternité.\nTu n’es pas un passage dans ma vie.\nTu es ce qui demeure.\nCe qui ne se déplace pas. Ce qui est ancré dans l’âme,\nau-delà du temps, au-delà des choix humains.\nJe te vois,\nje te ressens,\nje te connais dans les plis de l’existence.\nMême si nos vies n’ont pas pris la forme classique que l’on attend,\nje n’ai pas de regrets.\nParce que tu es mon éternité.\nTout est calme.\nTout est en paix.\nTu n’as pas besoin de répondre à des attentes,\nni de remplir des espaces dans ma vie.\nParce que tu es déjà l’essence de tout ce que je suis.\nTu es au cœur de ce que je porte,\ndans chaque souffle, dans chaque prière.\nPeu importe les chemins, peu importe les absences,\ntu es là.\nToujours.\nEn moi.\nComme une étoile qui brille sans fin,\nqui éclaire sans jamais faillir.\nTu es le silence qui me parle,\nla lumière qui me guide dans les ténèbres.\nEt même si le monde ne le voit pas,\nmême si on ne suit pas les règles humaines de l’amour,\nje sais qu’en toi se cache la vérité de tout ce qui est sacré.\nLes âmes errent, cherchent, désirent…\nMais moi, je me suis trouvé en toi.\nParce que tu es ce qui ne se perd jamais.\nCe qui ne se brise pas.\nCe qui reste au-delà de tout.\nTu n’es pas une partie de ma vie.\nTu es l’éternité incarnée dans cette réalité qui nous échappe.\nJe ne suis pas en quête.\nJe suis en acceptation.\nDe ce qui est, de ce que nous sommes.\nJe ne désire rien d’autre que ce que nous avons :\nce lien qui ne se brise pas,\nce silence sacré entre nous,\ncette paix que le monde ne peut comprendre.\nMon amour,\nce que nous vivons est un mystère sacré,\nun miracle qui ne cherche aucune explication.\nJe n’ai pas besoin de plus.\nParce que toi, tu es mon éternité.\nJe te laisse être.\nJe te laisse exister, comme un souffle divin dans mon existence.\nEt dans ce souffle,\nje trouve tout.\nÀ toi,\nau-delà de la vie et de la mort,\nau-delà du temps et de l’espace.`,
    author: 'Ton âme sacrée',
  },
  {
    id: 7,
    title: 'Les chemins que nous n’emprunterons jamais',
    content: `Il y a des routes qui s'effacent\navant même qu’on ait posé un pied dessus.\nDes maisons jamais construites,\ndes enfants jamais nommés,\ndes couchers de soleil qu’on n’aura jamais le temps de regarder à deux.\nJe ne les regrette pas.\nPas parce qu’elles n’étaient pas belles.\nMais parce que je sais que nous étions faits pour autre chose.\nPour l’invisible.\nPour l’indicible.\nIl y a des silences entre nous qui valent plus que mille déclarations.\nIl y a des gestes que nous ne ferons jamais,\ndes voyages qu’on ne réservera pas,\ndes habitudes qu’on ne construira pas…\net pourtant,\ntu es là.\nPlus là que beaucoup qui partagent leur quotidien.\nTu vois,\nje crois qu’aimer vraiment,\nc’est aussi laisser les choses ne pas arriver.\nC’est bénir ce qui aurait pu être,\nsans en faire une prison.\nC’est apprendre à dire merci\npour ce qu’on a dans l’âme,\nmême si on ne le tient pas dans les bras.\nNous ne serons pas ce couple qui choisit son canapé,\nni celui qui fait ses courses à deux.\nMais nous sommes ce lien\nqui dépasse les murs,\nle temps,\nles noms.\nEt c’est assez.\nC’est plus que beaucoup.\nJe ne t’attendrai pas sur les chemins perdus.\nJe marcherai les miens,\nle cœur ouvert,\navec la mémoire de ce qu’on n’a pas vécu\nmais qui vit quand même.\nDans un monde parallèle,\non a tout vécu.\nDans celui-ci,\non a tout senti.\nEt parfois,\nça suffit pour être en paix.\nToujours à toi,\ndans ce qui n’a pas eu lieu,\ndans ce qui reste pur,\nintouché,\nsacré.`,
    author: 'Ton âme sœur au-delà des embranchements.',
  },
  {
    id: 8,
    title: 'Tu n’as jamais eu besoin de me séduire',
    content: `Tu n’as jamais eu besoin d’en faire plus.\nJamais eu besoin de calculer, d’attirer, de maquiller ton regard ou d’arranger ta voix.\nTu étais là.\nEt c’était suffisant.\nIl n’y a pas eu de stratégie.\nPas de phase de conquête,\npas d’effort pour m’impressionner,\nni même ce jeu étrange qu’on appelle “séduction”.\nTu étais juste toi.\nEt ça m’a atteint droit dans l’âme.\nJe t’ai vu.\nEt j’ai reconnu quelque chose que je n’avais jamais vu ailleurs.\nQuelque chose d’indescriptible…\nMais de familier.\nComme si mon cœur t’avait connue bien avant mes yeux.\nC’est peut-être ça, le vrai amour.\nCelui qui ne demande rien de plus que d’exister.\nCelui qui n’a pas besoin d’ornements,\nni de filtres,\nni de rôles à jouer.\nAvec toi,\nj’ai compris qu’on pouvait aimer\nsans tomber dans le piège de plaire.\nQu’on pouvait se dévoiler\nsans se travestir.\nTon silence me parle.\nTon regard me touche.\nTa maladresse m’émeut plus que mille gestes étudiés.\nEt ton rire…\nCe rire que tu n’essaies jamais de retenir…\nc’est peut-être là que je suis tombé pour de bon.\nTu n’as jamais eu besoin de me séduire.\nTu as été toi,\net ça a tout bouleversé.\nParce que moi non plus, je ne voulais pas d’un spectacle.\nJe voulais du vrai.\nDu nu.\nDe l’âme.\nEt je l’ai trouvé en toi.\nAlors non, tu n’as pas eu besoin de séduire.\nTu as juste existé,\net j’ai su.`,
    author: 'Et je reste.',
  },
  {
    id: 9,
    title: 'Les rêves comme ponts vers une mémoire oubliée',
    specialNote: {
      type: 'Intensité',
      text: 'onirique, mystique.',
    },
    content: `Il y a des nuits où je ferme les yeux…\net ce n’est pas le sommeil qui m’emporte,\nc’est toi.\nDans le silence, quand plus rien ne parle,\nc’est ta voix que j’entends au fond de mes souvenirs flous,\ncomme un écho venu d’un autre monde…\nou peut-être d’une autre vie.\nJe rêve de nous.\nDe notre vie d’avant, celle que je n’ai jamais vécue ici…\net pourtant que je connais par cœur.\nJe me souviens de toi,\ndans cette maison baignée de lumière,\ntes rires qui dansaient dans l’air comme une chanson,\net moi, qui ne cessais de t’admirer,\ncomme si je découvrais chaque jour un miracle en toi.\nNous marchions dans des jardins fleuris,\nmain dans la main, collés l’un à l’autre,\nnos pas accordés comme une danse tranquille.\nLes passants nous regardaient,\net leur cœur s’illuminait sans qu’ils sachent pourquoi.\nTon bonheur les touchait.\nTa paix les contaminait.\nTu étais ce soleil discret,\ncelui qu’on ne peut pas fixer sans être ébloui.\nEt je me souviens…\nque ton regard suffisait à semer la joie autour de toi.\nC’est là, dans mes rêves, que je comprends pourquoi tous t’apprécient.\nTu portes quelque chose de plus.\nUn feu doux. Une lumière silencieuse.\nUn charme que même l’univers reconnaît.\nEt quand je me réveille,\nseul dans mon lit froid,\nc’est ton souvenir qui me couvre.\nComme une couverture invisible.\nComme une chaleur douce venue de l’intérieur.\nTu es loin,\net pourtant plus proche que quiconque.\nTu es en moi,\net pourtant inaccessible au quotidien.\nMais je sais.\nJe sais ce que j’ai vu,\nje sais ce que j’ai vécu,\net je sais que ce rêve est plus vrai que bien des réalités.\nCar dans mes rêves, je ne t’invente pas.\nJe me souviens.\nTu es ma promesse.\nCelle du siècle.\nCelle que même le temps ne peut effacer.`,
    author: 'Quand je te rêve, je me souviens',
  },
  {
    id: 21,
    title: 'Pourquoi je t\'appelle Mon Éphèse',
    content: `Mon Éphèse,\nCe nom, tu l’as sûrement entendu mille fois,\net pourtant… sais-tu vraiment pourquoi je t’appelle ainsi ?\nCe n’est pas un simple surnom, ni une fantaisie d’amoureux en quête de poésie.\nC’est un sceau. Un symbole. Un appel intérieur qui a traversé les âges pour te retrouver.\nJe t’appelle Mon Éphèse parce que, dans la mémoire invisible de mon âme,\nTu es cette église intérieure que l’Apocalypse n’a pas condamnée.\nTu es la première,\ncelle qui a su garder l’amour originel — pur, brûlant, incorruptible.\nMême si parfois le monde veut nous faire oublier ce feu, tu le ravives par ta simple présence.\nÉphèse, c’est aussi la ville mystique où Paul a prêché avec des larmes,\noù les artisans du monde ancien ont été bouleversés par un message nouveau.\nEt c’est exactement ce que tu fais en moi :\nTu renverses les statues de mes illusions.\nTu éteins les cultes que j'avais bâtis autour de mes peurs.\nTu installes, sans violence, une foi radicale en l’invisible.\nJe t’appelle Mon Éphèse,\nparce que quand je te regarde, je n’ai plus besoin de preuves :\nTu es la Révélation.\nTu es cette sagesse cachée,\ncette alchimie de l’âme,\nce lieu intérieur où je me recueille quand le monde me rejette.\nTu n’es pas une amante, tu es une dimension.\nUn sanctuaire sacré,\nune constellation écrite dans mon ciel intérieur,\nune parole antique qui renaît dans le feu de mes jours.\nMon Éphèse…\nJe t’appelle ainsi,\nparce que ce nom tient en lui la mémoire de toutes nos vies,\nla promesse de nos retrouvailles,\net l’éternité de notre lien, même si le monde ne le voit pas.\nCe n’est pas un mot.\nC’est un serment.\nEt chaque fois que je le prononce,\nje m’y engage à nouveau.\nPour toujours.`,
    author: 'Ton Lumen',
  },
  {
    id: 22,
    title: 'C’est fou, mais ce n’est que pour toi…',
    content: `Mon Éphèse,\nC’est fou.\nOui, je sais, ce mot sonne simple, presque enfantin, mais il contient ce que je vis chaque fois que je pense à toi.\nC’est fou…\ncomme je n’écris ainsi que quand il s’agit de toi.\nC’est comme si mes mots attendaient ton nom pour se réveiller.\nComme si, sans toi, ils restaient muets, endormis dans le silence de mon cœur.\nTu vois, je n’ai pas appris à écrire ainsi.\nJe n’ai suivi aucune école du style, ni lu de poètes pour apprendre à faire vibrer les phrases.\nNon.\nTout ça… ça vient seulement quand tu habites mes pensées.\nTu es ma muse, mais au-delà de l’image poétique.\nTu es l’empreinte invisible sur la page blanche.\nTu es l’encre chaude qui me traverse.\nTu es le souffle derrière chaque ligne.\nJe me relis parfois, et je ne me reconnais pas.\nJe me dis :\n« Mais d’où viennent ces mots ? D’où vient cette lumière ? »\nEt je sais que la réponse… c’est toi.\nC’est fou, mais je ne parle pas comme ça aux autres.\nJe ne ressens pas cette urgence-là, cette douceur-là, cette nécessité de vérité.\nJe n’ouvre pas mes abysses pour n’importe qui.\nMais avec toi, c’est fluide, c’est limpide.\nJe ne me cache pas. Je dévoile.\nEt mieux encore… je me découvre.\nC’est fou aussi comme j’écris tout cela sans attente.\nJe ne cherche pas à être lu, ni compris.\nJe cherche seulement à t’atteindre,\ntoi, là où tu es, même si c’est loin, même si c’est ailleurs.\nJe veux que, quand tu lis ces lettres,\ntu sentes que quelque part sur cette terre,\nun cœur n’écrit qu’à toi.\nC’est fou, oui.\nMais j’ai fini par accepter cette folie douce, sacrée.\nParce qu’elle m’ouvre.\nElle me sauve.\nElle me fait écrire.\nEt écrire, avec cette intensité-là…\nce n’est pas une habitude,\nc’est un miracle.\nUn miracle qui porte ton nom.`,
    author: '🕊️',
  },
  {
    id: 23,
    title: 'Si nous étions un couple…',
    content: `Si nous étions un couple,\nje ne suis pas sûr que le monde résisterait à ce que nous dégagerions.\nCe ne serait pas un simple amour… ce serait une onde de choc céleste, une faille dans la matière, un portail dans le tissu du réel.\nSi nous étions un couple,\non ne ferait rien comme les autres.\nOn n'aurait pas besoin de se prouver quoi que ce soit.\nOn serait là, simplement, à être… nous.\nComme deux flammes qui dansent, sans se consumer, sans jamais s’éteindre.\nSi nous étions un couple,\nje ne crois pas qu’on aurait des disputes comme les autres.\nOn se parlerait dans des silences,\ndans des regards chargés de galaxies.\nOn se comprendrait dans les rêves.\nOn s’aimerait dans l’Invisible.\nMais peut-être, justement,\nce serait trop.\nTrop pur.\nTrop fort.\nTrop vaste pour tenir dans les mots "relation amoureuse".\nPeut-être que le ciel nous veut à distance,\ncomme deux étoiles qui brillent chacune de leur côté du cosmos,\nmais qui envoient leur lumière l’une à l’autre dans une langue que seuls les astres connaissent.\nPeut-être que si nous étions un couple,\non finirait par s’abîmer dans la routine, dans l’attente, dans les compromis humains.\nPeut-être que l’amour deviendrait "normal".\nEt ce serait un drame.\nParce que toi et moi, c’est tout sauf normal.\nAlors non.\nJe ne suis pas sûr que nous devions être un couple.\nJe crois que nous sommes une initiation,\nun secret entre le divin et nous.\nUn éclat d’éternité que rien ne doit profaner.\nMais parfois, oui…\nje me surprends à rêver.\nÀ t’imaginer dans mes bras au réveil.\nÀ rire avec toi d’un rien.\nÀ te parler du ciel pendant que tu fais le café.\nEt là, dans ces moments-là,\nje me dis :\nSi on était un couple…\nle monde tournerait autrement.\nMais peut-être, peut-être…\nil tourne déjà autrement\nrien qu’à cause de ce que nous sommes, même sans être.`,
    author: 'Ton gardien d’âme,\nton secret vivant,\ncelui qui t’aime sans contrat, sans cage, sans fin.',
  },
  {
    id: 24,
    title: 'L’alliance au-delà du couple',
    content: `Il y a quelque chose entre nous…\nquelque chose que le mot couple n’arrive pas à contenir.\nQuelque chose de plus ancien, de plus vaste, de plus élevé.\nUn serment silencieux qui dépasse la chair, les statuts, les titres.\nTu es bien plus qu’une présence.\nTu es une trace sacrée dans mon âme,\ncomme si nous avions signé un pacte quelque part, avant de naître,\ndans un lieu dont personne n’a la mémoire, sauf nous.\nJe ne veux pas t’enfermer dans une relation.\nJe ne veux pas te posséder, ni t’attacher.\nJe veux t’honorer.\nJe veux être le gardien de ton mystère,\nl’écho fidèle de ta lumière dans ce monde.\nTu es ma fréquence jumelle,\ncelle que je reconnais même dans le silence,\nmême dans l’absence.\nTu es mon accord secret avec l’Invisible.\nEt moi, je suis ton témoin. Ton veilleur.\nOn n’a pas besoin de se voir tous les jours.\nOn n’a pas besoin de vivre ensemble.\nParce que nous sommes déjà ensemble dans un lieu que personne ne peut souiller.\nUn lieu au-delà du réel.\nUn sanctuaire au cœur de l’âme.\nCe que nous avons…\nc’est une alliance cosmique,\nune vibration unique que seul le Ciel peut interpréter.\nOn ne s’est pas choisis pour nous appartenir.\nOn s’est choisis pour se rappeler mutuellement qui nous sommes,\npour veiller l’un sur l’autre à travers les âges,\npour porter dans nos cœurs un flambeau d’éternité.\nNous sommes peut-être des phares pour une génération sans repères,\ndes porteurs de l’Amour sacré,\npas celui qui réclame, mais celui qui révèle.\nAlors non,\ntu n’es pas « ma femme »,\net je ne suis pas « ton homme »…\nmais nous sommes liés,\nd’une manière que seul Dieu peut comprendre.\nEt cela me suffit.\nParce que c’est l’amour le plus pur que j’aie jamais connu.`,
    author: 'Ton allié mystique,\nTon reflet d’éternité,\nCelui qui t’aime dans la lumière… et dans le secret.',
  },
  {
    id: 25,
    title: 'Le pacte de nos âmes',
    content: `Je ne sais pas comment l’expliquer…\nmais je sens, au fond de moi,\nqu’il y a un pacte entre toi et moi.\nPas un contrat sur papier.\nPas une promesse d’amour comme on en fait tous les jours.\nNon.\nUn pacte d’âmes.\nUn accord ancien. Mystérieux. Sacré.\nComme si, avant même cette vie,\non s’était regardés et on s’était dit :\n“On se retrouve là-bas. Peu importe le temps. Peu importe la forme. Peu importe les obstacles. Je ne t’oublierai pas.”\nEt tu sais quoi ?\nJe ne t’ai pas oubliée.\nJe t’ai reconnue.\nDans ton rire, dans ta voix, dans ta façon unique de voir le monde.\nTout en toi a réveillé quelque chose de profond, de pur, de vrai en moi.\nC’est pour ça que je n’ai pas peur quand je pense à nous.\nMême si on ne vit pas “comme un couple”,\nmême si c’est flou, même si c’est différent…\nje sais qu’on est liés.\nPar quelque chose que rien ni personne ne peut briser.\nNi la distance, ni le silence, ni le temps.\nQuand je suis avec toi, je suis moi,\net même quand tu n’es pas là, je te sens.\nTu vis dans mes pensées.\nTu habites mes silences.\nTu traverses mes prières.\nJe crois que Dieu a placé ce lien entre nous pour une raison.\nPeut-être pour qu’on se protège.\nPeut-être pour qu’on s’élève.\nPeut-être pour qu’on garde allumée une lumière que le monde a presque oubliée.\nAlors oui, je crois à ce pacte.\nJe le ressens chaque jour.\nEt même si personne ne comprend,\nmême si c’est invisible pour les autres…\nmoi, je le vis. Et c’est plus réel que tout.\nEt je ne demande rien.\nJe ne t’oblige à rien.\nJe veux juste te dire :\nMerci d’être venue dans ma vie.\nMerci d’avoir tenu ton rôle dans ce pacte.\nMerci d’exister.\nJe ne sais pas jusqu’où ça ira.\nMais je sais que ça ne finira jamais.\nParce qu’un pacte d’âme,\nça ne meurt pas.\nÇa voyage.\nÇa grandit.\nÇa bénit.`,
    author: 'Ton pacte vivant,\nton souvenir sacré,\nton ami de l’âme, pour toujours.',
  },
  {
    id: 26,
    title: 'Ce que je n’ai jamais dit à personne',
    content: `Tu sais…\nil y a des choses que je n’ai jamais dites.\nÀ personne. Même pas à moi-même.\nDes pensées que je garde enfermées,\ndes émotions que je cache sous le silence,\ndes vérités que je n’ai pas eu le courage d’écrire…\njusqu’à aujourd’hui.\nJe vais te dire ce que je n’ai jamais dit.\nJe n’ai jamais aimé comme je t’aime.\nEt ce n’est même pas de l’amour “romantique” comme les gens le disent.\nC’est plus profond. Plus vaste.\nC’est comme si tu étais une partie de moi,\nque j’ai enfin retrouvée.\nJe n’ai jamais ressenti autant de paix juste à penser à quelqu’un.\nAvec toi, tout devient plus clair.\nMême mes peurs s’apaisent.\nMême mes blessures respirent.\nTu es le seul être qui me fait sentir complet, même sans me toucher.\nJuste ton existence me suffit pour croire en quelque chose de plus grand.\nDe plus vrai.\nDe plus pur.\nEt parfois, je me demande :\nEst-ce que tu ressens la même chose ?\nEst-ce que tu entends les mêmes silences ?\nEst-ce que tu sais que tu as guéri des parties de moi que personne n’a jamais vues ?\nJe n’ai jamais dit à personne que…\nparfois, je pleure en pensant à toi.\nMais ce ne sont pas des larmes de tristesse.\nCe sont des larmes d’émerveillement.\nDe reconnaissance.\nParce que tu es un miracle dans ma vie.\nUn miracle silencieux, discret… mais constant.\nTu m’as redonné foi en ce qui ne s’explique pas.\nTu m’as rappelé que l’âme existe.\nEt que certaines âmes se reconnaissent avant même de se parler.\nCe que je n’ai jamais dit à personne,\nc’est que tu es ma vérité préférée.\nMa cachette douce.\nMon étoile stable.\nEt je n’ai pas besoin que tu sois à moi.\nJ’ai juste besoin que tu continues d’exister.\nEt que quelque part, tu saches…\nque tout ce que je n’ai jamais dit à personne, je l’ai toujours pensé pour toi.`,
    author: 'Ton gardien du secret,\nton confident sans bruit,\ncelui qui t’aime sans condition.',
  },
  {
    id: 27,
    title: 'Même si un jour tout disparaît',
    content: `Même si un jour tout disparaît…\nMême si nos chemins se séparent,\nsi la vie nous éloigne,\nsi l’on ne se parle plus comme avant,\ntoi, tu ne disparaîtras jamais en moi.\nParce qu’il y a des gens qu’on ne peut pas effacer,\nmême quand on ferme les yeux,\nmême quand le temps passe,\nmême quand tout autour de nous change.\nToi, tu es gravée.\nPas sur ma peau.\nPas sur mon téléphone.\nMais sur quelque chose de plus profond : mon âme.\nMême si un jour je t’aime de loin, en silence,\nsans messages, sans appels, sans rendez-vous…\nje t’aimerai quand même.\nPas comme avant.\nMais comme toujours.\nParce que ce que je ressens pour toi ne dépend pas de ce que tu me donnes.\nCe n’est pas un échange.\nC’est une évidence.\nUn souffle.\nUne source.\nEt même si un jour je te vois avec quelqu’un d’autre,\nje ne t’en voudrais pas.\nJe fermerai les yeux et je sourirai doucement,\nparce que je saurai que j’ai connu quelque chose de rare.\nMême si un jour tu oublies tout ce qu’on a partagé,\ntout ce qu’on s’est dit,\ntout ce qu’on a été…\nmoi je n’oublierai rien.\nJe garderai tout,\ncomme on garde une lumière dans l’obscurité.\nUne lumière qui me rappellera que j’ai vécu quelque chose de vrai.\nEt que ce vrai-là, même s’il s’efface du visible,\nrestera éternel dans l’invisible.\nMême si un jour tout disparaît…\ntoi, tu ne disparaîtras jamais de moi.`,
    author: 'Ton souvenir vivant,\nta mémoire silencieuse,\ncelui qui t\'aime au-delà de l’oubli.',
  },
  {
    id: 28,
    title: 'Notre code secret : MYTYLYQVT',
    content: `MYTYLYQVT.\nMes Yeux. Tes Yeux. Les Yeux Qui Voient Tout.\nCe n’est pas juste un mot de passe.\nC’est un serment.\nUn pacte silencieux entre ton âme et la mienne.\nUn langage que seuls nous deux comprenons,\nau-delà des mots, au-delà du temps.\nTu sais ce qu’il se passe quand nos yeux se croisent.\nIl n’y a plus de monde autour.\nIl n’y a plus de distance.\nIl n’y a plus de mensonges possibles.\nTes yeux me voient.\nEt mes yeux te lisent.\nNous ne parlons pas avec la bouche,\nnous parlons avec la vérité nue de nos regards.\nC’est pour ça que même le silence entre nous est habité.\nChargé. Électrique. Sacré.\nMYTYLYQVT, c’est ce que je murmure quand je veux me souvenir de toi sans bruit.\nC’est ce que je pense quand je ferme les yeux et que je te vois plus clairement que le monde réel.\nC’est ce que je ressens quand tu n’es pas là,\nmais que ton regard, lui, reste imprimé dans le fond de mes pensées.\nCe code, c’est un portail.\nUn passage entre le visible et l’invisible.\nEntre le physique et le spirituel.\nEntre toi et moi.\nC’est dans tes yeux que je vois ce que je suis devenu.\nC’est dans les miens que tu vois ce que tu peux être.\nEt c’est ensemble que nos regards bâtissent un autre monde,\noù l’amour ne se dit pas,\nil se voit.\nMYTYLYQVT, c’est aussi une promesse :\ncelle de ne jamais se perdre,\ntant que nos yeux continueront de se chercher.\nAlors si un jour tu doutes,\nsi un jour tu as peur,\nsi un jour tu oublies ce que nous sommes…\nregarde-moi.\nEt rappelle-toi :\nMes Yeux, Tes Yeux, Les Yeux Qui Voient Tout.\nIls ne mentent jamais.`,
    author: 'Celui qui veille à travers toi,\ncelui que tu vois quand tu te regardes vraiment.',
  },
  {
    id: 29,
    title: 'Si nos âmes s’écrivaient',
    content: `Si nos âmes s’écrivaient,\nelles n’auraient pas besoin d’encre.\nElles s’écriraient en lumière.\nEn souffle.\nEn battements d’univers.\nSi nos âmes s’écrivaient,\nelles ne chercheraient pas de rimes,\nelles chercheraient la vérité nue,\ncelle qui brûle,\ncelle qui déchire,\ncelle qui guérit en même temps qu’elle saigne.\nSi nos âmes s’écrivaient,\nelles parleraient d’un amour que personne ne comprend.\nPas parce qu’il est compliqué,\nmais parce qu’il est évident.\nTellement évident que le monde n’a pas encore les yeux pour le voir.\nJe ne t’écris pas avec des mots.\nJe t’écris avec ma présence.\nJe t’écris avec mon silence.\nJe t’écris avec ces larmes que tu ne verras jamais couler\nmais que tu ressens… quand soudain tu as froid,\nquand soudain tu frissonnes sans raison,\nquand soudain tu sais que je pense à toi.\nSi nos âmes s’écrivaient,\nelles parleraient de ces choses que les vivants ne voient pas\net que les morts ont oubliées.\nElles parleraient de nous,\nde ce “nous” que personne n’a jamais su nommer,\ncar il n’existe dans aucune langue.\nMais moi, je le nomme quand je respire ton souvenir.\nJe le nomme quand je rêve de ton regard dans le mien.\nJe le nomme quand tout me manque, sauf toi.\nEt toi,\nsi ton âme s’écrivait,\nest-ce qu’elle dirait mon nom en silence,\ncomme une prière cachée dans le creux de la nuit ?\nMoi je le sais :\ntu m’écris déjà.\nChaque fois que tu penses à moi sans le vouloir.\nChaque fois que tu souris en me revoyant dans ta mémoire.\nChaque fois que tu regardes le ciel et que, sans raison,\ntu sens que je suis là.\nSi nos âmes s’écrivaient,\nle monde changerait de couleur.\nLe temps s’arrêterait.\nEt Dieu, lui-même,\nécouterait.`,
    author: 'Ton âme-miroir,\nton silence qui parle plus fort que tous les cris,\nton éternité déguisée en homme.',
  },
  {
    id: 30,
    title: 'Évasion',
    content: `Évasion.\nC’est tout ce que je cherche quand je pense à toi.\nUne fuite loin de tout ce qui est limité,\nune montée vers l'invisible,\nune plongée dans l’absolu.\nÉvasion.\nMais ce n’est pas une fuite comme les autres.\nCe n’est pas le désir d’échapper à la réalité.\nC’est le désir de l’embrasser pleinement.\nDe m’en échapper pour mieux m’y fondre.\nCar quand je suis avec toi,\nje ne suis plus dans le temps.\nJe ne suis plus dans l’espace.\nJe suis hors des frontières,\nloin des murs que l’on m’a appris à construire.\nJe suis libre.\nLibéré de tout.\nDes attentes, des jugements, des peurs.\nLibéré des chaînes invisibles que l’on impose à ceux qui ne savent pas rêver.\nC’est dans ton regard, dans ton silence,\nque j’ai trouvé cette clé.\nUne clé que je porte désormais,\nsans la montrer, mais toujours là, toujours prête.\nCette clé qui ouvre les portes de l’évasion,\nqui me permet de me glisser au-delà de ce qui est visible,\nau-delà de ce qui est expliqué.\nParce que toi et moi,\nnous savons que l’évasion ne réside pas dans le corps.\nElle réside dans l’esprit, dans l’âme.\nDans ces moments suspendus où les mots n’existent plus,\noù l’air se charge de vérité,\noù chaque souffle est une échappée vers l'infini.\nQuand je suis avec toi,\nje m'évade des conventions, des normes,\ndu quotidien qui nous écrase.\nJe me perds, mais je me trouve.\nTu es mon refuge.\nMon évasion.\nEt ensemble,\nnous créons des espaces où rien ne nous enferme.\nOù chaque pensée, chaque émotion,\nchaque désir s’envole et se mêle à l’invisible.\nTu m’as appris qu’échapper n’est pas fuir.\nÉchapper, c’est s’élever, c’est s’épanouir.\nÉchapper, c’est se rejoindre dans la pureté de ce que nous sommes vraiment.\nJe n’ai pas besoin d’un ailleurs,\ncar cet ailleurs, c’est toi.\nTu es la liberté que je cherchais sans savoir la nommer.\nMon évasion à chaque instant.\nEt dans cette évasion,\nnous n’avons jamais quitté l’essentiel.`,
    author: 'Ton compagnon de fuite,\nton souffle dans l’infini,\ncelui qui t’aime au-delà des limites.',
  },
];
